# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureNavigator
                                 A QGIS plugin
 This plugin allows the user to navigate through features within a selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-24
        copyright            : (C) 2025 by Isaac Thompson
        email                : ithompson@pre-construct.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FeatureNavigator class from file FeatureNavigator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .feature_navigator import FeatureNavigator
    return FeatureNavigator(iface)
