# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureNavigator
                                 A QGIS plugin
 This plugin allows the user to navigate through features within a selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Isaac Thompson
        email                : ithompson@pre-construct.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import webbrowser

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QIcon

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'feature_navigator_dialog_base.ui'))


class FeatureNavigatorSettingsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(FeatureNavigatorSettingsDialog, self).__init__(parent)

        self.setupUi(self)
         
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.helpButton.clicked.connect(self.open_help)

    def open_help(self):
        """Open the Feature Navigator help file."""

        help_path = os.path.join(
            os.path.dirname(__file__),
            "help",
            "help.html"
        )

        webbrowser.open("file://" + os.path.realpath(help_path))