# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureNavigator
                                 A QGIS plugin
 This plugin allows the user to navigate through features within a selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Isaac Thompson
        email                : ithompson@pre-construct.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtWidgets import QAction, QDialog, QMessageBox, QShortcut
from qgis.PyQt.QtGui import QIcon, QKeySequence
from qgis.core import QgsFeatureRequest, QgsMapLayerProxyModel, QgsProject
from PyQt5.QtCore import QTimer
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .feature_navigator_dockwidget import FeatureNavigatorDockWidget
from .feature_navigator_dialog import FeatureNavigatorSettingsDialog
import os.path



class FeatureNavigator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FeatureNavigator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Feature Navigator')
        # TODO: We are going to let the user set this up in a future iteration

        #print "** INITIALIZING FeatureNavigator"

        self.pluginIsActive = False
        self.dockwidget = None

        # Internal state must exist even if run() has never been opened
        self.feature_ids = []
        self.current_index = -1
        self.current_layer = None
        self.has_selected_feature = False
        self.ignore_selection_change = False

        # Optional runtime objects
        self.timer = None
        self.spacebar_shortcut = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FeatureNavigator', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)
        
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/feature_navigator/icons/feature_navigator_icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Navigate features in selected layer'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed."""

        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        old_layer = self.safe_current_layer()
        if old_layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        old_layer = self.safe_current_layer()
        if old_layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)

        try:
            QgsProject.instance().removeAll.disconnect(self.clear_plugin_state)
        except TypeError:
            pass

        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

        self.actions = []
        self.dockwidget = None
        self.spacebar_shortcut = None
        self.timer = None
        self.current_layer = None
        self.feature_ids = []
        self.current_index = -1
        self.has_selected_feature = False
        self.pluginIsActive = False
        
    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            if self.dockwidget is None:
                # Create the dockwidget and setup
                self.dockwidget = FeatureNavigatorDockWidget()
                self.dockwidget.settingsButton.clicked.connect(self.show_settings_dialog)
                self.dockwidget.selectedFeatureLabel.setVisible(False)

                # Internal state
                self.feature_ids = []
                self.current_index = -1
                self.current_layer = None
                self.has_selected_feature = False
                self.ignore_selection_change = False

                # Setup map layer combo box
                self.dockwidget.mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.HasGeometry)
                self.dockwidget.mMapLayerComboBox.layerChanged.connect(self.reset_feature_index)

                # Setup navigation buttons
                self.dockwidget.previousButton.clicked.connect(self.previous_feature)
                self.dockwidget.nextButton.clicked.connect(self.next_feature)
                self.dockwidget.playButton.clicked.connect(self.start_auto_play)
                self.dockwidget.pauseButton.clicked.connect(self.stop_auto_play)
                
                # Prevent buttons from being triggered by Space when they have focus
                self.dockwidget.previousButton.setFocusPolicy(Qt.NoFocus)
                self.dockwidget.nextButton.setFocusPolicy(Qt.NoFocus)
                self.dockwidget.playButton.setFocusPolicy(Qt.NoFocus)
                self.dockwidget.pauseButton.setFocusPolicy(Qt.NoFocus)
                self.dockwidget.settingsButton.setFocusPolicy(Qt.NoFocus)
                
                # Space bar shortcut for play/pause
                self.spacebar_shortcut = QShortcut(QKeySequence(Qt.Key_Space), self.dockwidget)
                self.spacebar_shortcut.activated.connect(self.toggle_play_pause_from_spacebar)
                self.spacebar_shortcut.setEnabled(False)  # default until settings are loaded

                # Setup timer
                self.timer = QTimer()
                interval = QSettings().value("FeatureNavigator/playbackInterval", 1000, type=int)
                self.timer.setInterval(interval)
                self.timer.timeout.connect(self.next_feature)

                # Setup default states
                self.dockwidget.previousButton.setEnabled(False)
                self.dockwidget.nextButton.setEnabled(False)
                self.dockwidget.playButton.setEnabled(False)
                self.dockwidget.pauseButton.setEnabled(False)
              
              # Connect plugin close signal
                self.dockwidget.closingPlugin.connect(self.onClosePlugin)            
                QgsProject.instance().removeAll.connect(self.clear_plugin_state)
                
            # Show the dockwidget
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.errorLabel.setStyleSheet("color: red")
            self.dockwidget.errorLabel.setVisible(False)
            self.dockwidget.show()
            
            self.dockwidget.setFocusPolicy(Qt.StrongFocus)
            self.dockwidget.setFocus()
            
            # Apply saved space bar setting
            settings = QSettings()
            spacebar_enabled = settings.value("FeatureNavigator/enableSpacebarPlayPause", False, type=bool)
            if self.spacebar_shortcut is not None:
                self.spacebar_shortcut.setEnabled(spacebar_enabled)

            

            # ✅ Set active layer *and trigger logic*
            active_layer = self.iface.activeLayer()
            if active_layer and active_layer.isValid() and active_layer.type() == active_layer.VectorLayer and active_layer.geometryType() >= 0:
                self.dockwidget.mMapLayerComboBox.setLayer(active_layer)
                self.reset_feature_index(active_layer)  # <-- this is essential
            else:
                self.dockwidget.mMapLayerComboBox.setLayer(None)
                self.reset_feature_index(None)
        
    def reset_feature_index(self, layer):
        """Reset the feature list and index when a new layer is selected."""

        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        self.dockwidget.selectedFeatureLabel.setVisible(False)
        self.dockwidget.selectedFeatureLabel.setText("")
        self.dockwidget.errorLabel.setVisible(False)
        self.dockwidget.pauseButton.setEnabled(False)
        self.dockwidget.mMapLayerComboBox.setEnabled(True)

        old_layer = self.safe_current_layer()
       
        if old_layer and old_layer != layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)

        if not layer:
            if old_layer:
                try:
                    old_layer.removeSelection()
                except RuntimeError:
                    pass

            self.current_layer = None
            self.feature_ids = []
            self.current_index = -1
            self.has_selected_feature = False

            self.dockwidget.errorLabel.setText("No layer selected")
            self.dockwidget.errorLabel.setVisible(True)
            self.disable_navigation()
            return

        if old_layer and old_layer != layer:
            try:
                old_layer.removeSelection()
            except RuntimeError:
                pass

        self.current_layer = layer
        self.connect_layer_selection_signal(self.current_layer)
        self.connect_layer_feature_signals(self.current_layer)
        self.has_selected_feature = False
        self.current_index = -1
        self.refresh_feature_list(preserve_position=False)
        return

    def connect_layer_selection_signal(self, layer):
        """Connect to the selected layer's selectionChanged signal."""
        if not layer:
            return

        try:
            layer.selectionChanged.connect(self.on_layer_selection_changed)
        except TypeError:
            # Already connected
            pass

    def disconnect_layer_selection_signal(self, layer):
        """Disconnect from the previous layer's selectionChanged signal."""
        if not layer:
            return

        try:
            layer.selectionChanged.disconnect(self.on_layer_selection_changed)
        except TypeError:
            # Was not connected
            pass
            
    def next_feature(self):
        """Move forward in the feature list."""
        if not self.feature_ids:
            return

        if not self.has_selected_feature:
            # First click/play should go to feature 1
            self.current_index = 0
            self.has_selected_feature = True
        else:
            self.current_index = (self.current_index + 1) % len(self.feature_ids)

        self.dockwidget.selectedFeatureLabel.setVisible(True)
        self.select_feature()
    
    def on_layer_selection_changed(self, selected, deselected, clearAndSelect):
        """Jump navigator index to a user-selected feature in the current layer."""
        if self.ignore_selection_change:
            return

        if not self.current_layer or not self.feature_ids:
            return

        if not selected:
            return

        # Use the first selected feature id
        fid = next(iter(selected), None)
        if fid is None:
            return

        if fid not in self.feature_ids:
            return

        self.current_index = self.feature_ids.index(fid)
        self.has_selected_feature = True
        self.dockwidget.selectedFeatureLabel.setVisible(True)
        self.update_selected_feature_label()


    def previous_feature(self):
        """Move backward in the feature list."""
        if not self.feature_ids:
            return
        self.current_index = (self.current_index - 1 + len(self.feature_ids)) % len(self.feature_ids)
        self.select_feature()
     
    def select_feature(self):
        """Select and zoom to the current feature."""
        if not self.current_layer or not self.feature_ids:
            return

        fid = self.feature_ids[self.current_index]

        # Make sure this layer is the active layer in QGIS
        self.iface.setActiveLayer(self.current_layer)

        # Ensure visibility of layer and parent groups
        layer_node = self.iface.layerTreeView().layerTreeModel().rootGroup().findLayer(self.current_layer.id())
        visibility_changed = False

        if layer_node:
            if not layer_node.itemVisibilityChecked():
                layer_node.setItemVisibilityChecked(True)
                visibility_changed = True

            parent = layer_node.parent()
            while parent and parent.nodeType() == 0:  # 0 = Group
                if not parent.itemVisibilityChecked():
                    parent.setItemVisibilityChecked(True)
                    visibility_changed = True
                parent = parent.parent()

        # Notify the user if we had to change visibility
        if visibility_changed:
            QMessageBox.information(
                self.iface.mainWindow(),
                "Feature Navigator",
                "Layer/group(s) was toggled <strong>ON</strong> so the selected layer could be visible."
            )

        # Clear previous selection and select current feature
        self.ignore_selection_change = True
        try:
            self.current_layer.removeSelection()
            self.current_layer.selectByIds([fid])
        finally:
            self.ignore_selection_change = False
        
        # Zoom to feature with fixed buffer (e.g. 5 map units)
        feature = next(self.current_layer.getFeatures(QgsFeatureRequest(fid)), None)
        if feature:
            geom = feature.geometry()
            if geom:
                extent = geom.boundingBox()
                buffer_size = QSettings().value("FeatureNavigator/zoomBuffer", 1, type=int)

                # Manually expand the extent
                buffered_extent = extent.buffered(buffer_size)

                self.iface.mapCanvas().setExtent(buffered_extent)
                self.iface.mapCanvas().refresh()
                self.update_selected_feature_label()
    
    def update_selected_feature_label(self):
        """Update the 'Feature X of Y' label."""
        if self.current_index >= 0 and self.feature_ids:
            current = self.current_index + 1
            total = len(self.feature_ids)
            self.dockwidget.selectedFeatureLabel.setText(f"Feature {current} of {total}")
    
    def toggle_play_pause_from_spacebar(self):
        """Toggle play/pause using the space bar shortcut."""
        if not self.dockwidget:
            return

        settings = QSettings()
        enabled = settings.value("FeatureNavigator/enableSpacebarPlayPause", False, type=bool)
        if not enabled:
            return

        if not self.feature_ids or len(self.feature_ids) <= 1:
            return

        if self.timer is not None and self.timer.isActive():
            self.stop_auto_play()
        else:
            self.start_auto_play()
        
    def start_auto_play(self):
        """Start automated navigation."""
        if not self.feature_ids:
            return

        self.next_feature()  # First play goes to feature 1

        if self.timer is not None:
            self.timer.start()

        self.dockwidget.playButton.setEnabled(False)
        self.dockwidget.pauseButton.setEnabled(True)
        self.dockwidget.nextButton.setEnabled(False)
        self.dockwidget.previousButton.setEnabled(False)
        self.dockwidget.mMapLayerComboBox.setEnabled(False)


    def stop_auto_play(self):
        """Stop automated navigation."""
        if self.timer is not None:
            self.timer.stop()

        self.dockwidget.playButton.setEnabled(True)
        self.dockwidget.pauseButton.setEnabled(False)
        self.dockwidget.mMapLayerComboBox.setEnabled(True)

        if len(self.feature_ids) > 1:
            self.dockwidget.nextButton.setEnabled(True)
            self.dockwidget.previousButton.setEnabled(True)
            
    def disable_navigation(self):
        """Disable all navigation-related controls."""
        self.dockwidget.previousButton.setEnabled(False)
        self.dockwidget.nextButton.setEnabled(False)
        self.dockwidget.playButton.setEnabled(False)
        self.dockwidget.pauseButton.setEnabled(False)


    def show_settings_dialog(self):
        """Open settings dialog and apply only if OK was clicked."""
        dialog = FeatureNavigatorSettingsDialog()

        settings = QSettings()
        current_interval_ms = settings.value("FeatureNavigator/playbackInterval", 1000, type=int)
        current_buffer_m = settings.value("FeatureNavigator/zoomBuffer", 1, type=int)
        current_spacebar_enabled = settings.value("FeatureNavigator/enableSpacebarPlayPause", False, type=bool)

        dialog.speedSpinBox.setValue(current_interval_ms // 1000)
        dialog.bufferSpinBox.setValue(current_buffer_m)
        dialog.spacebarcheckBox.setChecked(current_spacebar_enabled)

        if dialog.exec_() == QDialog.Accepted:
            new_interval_ms = dialog.speedSpinBox.value() * 1000
            new_buffer_m = dialog.bufferSpinBox.value()
            new_spacebar_enabled = dialog.spacebarcheckBox.isChecked()

            settings.setValue("FeatureNavigator/playbackInterval", new_interval_ms)
            settings.setValue("FeatureNavigator/zoomBuffer", new_buffer_m)
            settings.setValue("FeatureNavigator/enableSpacebarPlayPause", new_spacebar_enabled)

            if self.timer is not None:
                self.timer.setInterval(new_interval_ms)

            if self.spacebar_shortcut is not None:
                self.spacebar_shortcut.setEnabled(new_spacebar_enabled)
                
                
     # --------------------------------------------------------------------------
    # FEATURE LIST AUTO-REFRESH LOGIC
    # --------------------------------------------------------------------------

    def connect_layer_feature_signals(self, layer):
        """Connect to layer signals that affect the feature list."""
        if not layer:
            return

        try:
            layer.featureAdded.connect(self.on_layer_feature_added)
        except TypeError:
            pass

        try:
            layer.featureDeleted.connect(self.on_layer_feature_deleted)
        except TypeError:
            pass


    def disconnect_layer_feature_signals(self, layer):
        """Disconnect from layer signals that affect the feature list."""
        if not layer:
            return

        try:
            layer.featureAdded.disconnect(self.on_layer_feature_added)
        except TypeError:
            pass

        try:
            layer.featureDeleted.disconnect(self.on_layer_feature_deleted)
        except TypeError:
            pass


    def refresh_feature_list(self, preserve_position=True, deleted_fid=None):
        """Rebuild feature id list while preserving current navigation position."""
        layer = self.safe_current_layer()
        if not layer:
            self.current_layer = None
            self.feature_ids = []
            self.current_index = -1
            self.has_selected_feature = False
            self.disable_navigation()
            return

        old_feature_ids = list(self.feature_ids)
        old_index = self.current_index

        current_fid = None
        if preserve_position and old_feature_ids and 0 <= old_index < len(old_feature_ids):
            current_fid = old_feature_ids[old_index]

        self.feature_ids = [f.id() for f in layer.getFeatures()]
        self.feature_ids.sort()
        num_features = len(self.feature_ids)

        if num_features == 0:
            self.current_index = -1
            self.has_selected_feature = False
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
            self.dockwidget.errorLabel.setText("No features in currently selected layer")
            self.dockwidget.errorLabel.setVisible(True)

            if self.timer is not None and self.timer.isActive():
                self.timer.stop()

            self.disable_navigation()
            self.dockwidget.mMapLayerComboBox.setEnabled(True)
            return

        if preserve_position and current_fid in self.feature_ids:
            self.current_index = self.feature_ids.index(current_fid)
        elif deleted_fid is not None and old_feature_ids:
            deleted_index = old_feature_ids.index(deleted_fid) if deleted_fid in old_feature_ids else old_index

            if deleted_index >= len(self.feature_ids):
                self.current_index = len(self.feature_ids) - 1
            else:
                self.current_index = deleted_index
        else:
            if not preserve_position:
                self.current_index = -1
                self.has_selected_feature = False
            elif old_index < 0:
                self.current_index = -1
                self.has_selected_feature = False
            elif old_index >= len(self.feature_ids):
                self.current_index = len(self.feature_ids) - 1
            else:
                self.current_index = old_index

        if num_features == 1:
            self.dockwidget.errorLabel.setText("Only single feature in selected layer")
            self.dockwidget.errorLabel.setVisible(True)
        else:
            self.dockwidget.errorLabel.setVisible(False)

        is_playing = self.timer is not None and self.timer.isActive()

        self.dockwidget.playButton.setEnabled(num_features > 1 and not is_playing)
        self.dockwidget.pauseButton.setEnabled(num_features > 1 and is_playing)
        self.dockwidget.previousButton.setEnabled(num_features > 1 and not is_playing)
        self.dockwidget.nextButton.setEnabled(num_features > 1 and not is_playing)

        if self.current_index >= 0 and self.has_selected_feature:
            self.dockwidget.selectedFeatureLabel.setVisible(True)
            self.update_selected_feature_label()
        else:
            self.current_index = -1
            self.has_selected_feature = False
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")


    def on_layer_feature_added(self, fid):
        """Triggered when a feature is added."""
        if self.ignore_selection_change:
            return

        self.refresh_feature_list(preserve_position=True)


    def on_layer_feature_deleted(self, fid):
        """Triggered when a feature is deleted."""
        if self.ignore_selection_change:
            return

        self.refresh_feature_list(preserve_position=True, deleted_fid=fid)

        # Do not auto-select or auto-zoom after deletion.
        # Leave the canvas/view where it is, and wait for the user's next input.
        self.has_selected_feature = False

        if self.dockwidget:
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
        
    def safe_current_layer(self):
        """Return current layer if still valid, otherwise None."""
        layer = getattr(self, "current_layer", None)

        if layer is None:
            self.current_layer = None
            return None

        try:
            _ = layer.id()
            return layer
        except RuntimeError:
            self.current_layer = None
            return None


    def clear_plugin_state(self):
        """Clear plugin state safely when project/layers are removed."""
        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        old_layer = self.safe_current_layer()
        if old_layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)
            try:
                old_layer.removeSelection()
            except RuntimeError:
                pass

        self.current_layer = None
        self.feature_ids = []
        self.current_index = -1
        self.has_selected_feature = False

        if self.dockwidget:
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
            self.dockwidget.errorLabel.setVisible(False)
            self.dockwidget.mMapLayerComboBox.setLayer(None)
            self.dockwidget.mMapLayerComboBox.setEnabled(True)
            self.disable_navigation()
        


