# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureNavigator
                                 A QGIS plugin
 This plugin allows the user to navigate through features within a selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Isaac Thompson
        email                : iswaldeen@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtWidgets import QAction, QDialog, QMessageBox, QShortcut
from qgis.PyQt.QtGui import QDesktopServices, QIcon, QKeySequence
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QTimer, QElapsedTimer, QUrl
from qgis.core import (
    QgsFeatureRequest,
    QgsMapLayerProxyModel,
    QgsProject,
    QgsLayerTreeNode,
)
# Initialize Qt resources from file resources.py
from . import resources

# Import the code for the DockWidget
from .feature_navigator_dockwidget import FeatureNavigatorDockWidget
from .feature_navigator_dialog import FeatureNavigatorSettingsDialog
import os.path

try:
    NO_FOCUS = Qt.FocusPolicy.NoFocus
    STRONG_FOCUS = Qt.FocusPolicy.StrongFocus
    LEFT_DOCK_WIDGET_AREA = Qt.DockWidgetArea.LeftDockWidgetArea
    KEY_SPACE = Qt.Key.Key_Space
    DIALOG_ACCEPTED = QDialog.DialogCode.Accepted
except AttributeError:
    NO_FOCUS = Qt.NoFocus
    STRONG_FOCUS = Qt.StrongFocus
    LEFT_DOCK_WIDGET_AREA = Qt.LeftDockWidgetArea
    KEY_SPACE = Qt.Key_Space
    DIALOG_ACCEPTED = QDialog.Accepted



class FeatureNavigator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale", "en", type=str)[:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FeatureNavigator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            if self.translator.load(locale_path):
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Feature Navigator')
        # TODO: We are going to let the user set this up in a future iteration

        #print "** INITIALIZING FeatureNavigator"

        self.pluginIsActive = False
        self.dockwidget = None
        
        self.feature_id_to_index = {}
        self.is_dark_mode = False

        # Internal state must exist even if run() has never been opened
        self.feature_ids = []
        self.current_index = -1
        self.current_layer = None
        self.has_selected_feature = False
        self.ignore_selection_change = False
        self.selected_features_only = False
        self.loop_navigation_enabled = False
        self.nav_slider_enabled = True
        self.ignore_slider_change = False
        self.selected_feature_ids_cache = []
        self.user_has_selected_layer = False
        self.suppress_layer_change = False

        # Optional runtime objects
        self.timer = None
        self.spacebar_shortcut = None
        
        self.playback_interval_ms = 1000
        self.remaining_interval_ms = None
        self.playback_elapsed_timer = QElapsedTimer()


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FeatureNavigator', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)
        
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action
    
    def is_qgis_dark_theme(self):
        """Return True when QGIS is using a dark UI theme."""
        try:
            return self.iface.mainWindow().palette().window().color().lightness() < 128
        except RuntimeError:
            return False

    def themed_icon_path(self, light_icon_name, dark_icon_name):
        """Return the best icon path for the current QGIS theme."""
        icon_name = dark_icon_name if self.is_qgis_dark_theme() else light_icon_name
        icon_path = os.path.join(self.plugin_dir, "icons", icon_name)

        if os.path.exists(icon_path):
            return icon_path

        # Fallback to the light icon if the dark-mode variant is missing.
        fallback_path = os.path.join(self.plugin_dir, "icons", light_icon_name)
        return fallback_path if os.path.exists(fallback_path) else ""

    def open_help_document(self):
        """Open the plugin help document in the user's default browser."""
        help_path = os.path.join(self.plugin_dir, "help", "help.html")

        if not os.path.exists(help_path):
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Feature Navigator",
                "The help document could not be found."
            )
            return

        QDesktopServices.openUrl(QUrl.fromLocalFile(help_path))

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/feature_navigator/icons/feature_navigator_icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Navigate features in selected layer'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )

        self.add_action(
            self.themed_icon_path("settings.png", "settings_darkmode.png"),
            text=self.tr(u"Settings"),
            callback=self.show_settings_dialog,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        self.add_action(
            self.themed_icon_path("question_mark.png", "question_mark_darkmode.png"),
            text=self.tr(u"Help"),
            callback=self.open_help_document,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed."""

        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        old_layer = self.safe_current_layer()
        if old_layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)

        self.pluginIsActive = False


    def unload(self):
        """Remove the plugin menu items, toolbar icons, and signal connections."""

        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        old_layer = self.safe_current_layer()
        if old_layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)

        try:
            QgsProject.instance().cleared.disconnect(self.clear_plugin_state)
        except TypeError:
            pass

        try:
            QgsProject.instance().layerWillBeRemoved.disconnect(
                self.on_layer_will_be_removed
            )
        except TypeError:
            pass

        try:
            QgsProject.instance().layersAdded.disconnect(
                self.on_project_layers_added
            )
        except TypeError:
            pass

        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

        self.actions = []
        self.dockwidget = None
        self.spacebar_shortcut = None
        self.timer = None
        self.current_layer = None
        self.feature_ids = []
        self.feature_id_to_index = {}
        self.current_index = -1
        self.has_selected_feature = False
        self.pluginIsActive = False
        
    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            if self.dockwidget is None:
                # Create the dockwidget and setup
                self.dockwidget = FeatureNavigatorDockWidget()
                
                required_widgets = (
                    "settingsButton",
                    "selectedFeatureLabel",
                    "mMapLayerComboBox",
                    "previousButton",
                    "nextButton",
                    "playButton",
                    "pauseButton",
                    "navhorizontalSlider",
                    "errorLabel",
                )

                missing_widgets = [
                    widget_name
                    for widget_name in required_widgets
                    if not hasattr(self.dockwidget, widget_name)
                ]

                if missing_widgets:
                    QMessageBox.critical(
                        self.iface.mainWindow(),
                        "Feature Navigator",
                        "The plugin UI is missing required widget(s): "
                        + ", ".join(missing_widgets)
                    )
                    self.pluginIsActive = False
                    self.dockwidget = None
                    return
                    
                self.dockwidget.settingsButton.clicked.connect(self.show_settings_dialog)
                self.dockwidget.selectedFeatureLabel.setVisible(False)

                # Internal state
                self.feature_ids = []
                self.current_index = -1
                self.current_layer = None
                self.has_selected_feature = False
                self.ignore_selection_change = False

                # Setup map layer combo box
                self.dockwidget.mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.HasGeometry)
                self.dockwidget.mMapLayerComboBox.layerChanged.connect(self.on_combo_layer_changed)

                # Setup navigation buttons
                self.dockwidget.previousButton.clicked.connect(self.previous_feature)
                self.dockwidget.nextButton.clicked.connect(self.next_feature)
                self.dockwidget.playButton.clicked.connect(self.start_auto_play)
                self.dockwidget.pauseButton.clicked.connect(self.stop_auto_play)
                
                self.dockwidget.navhorizontalSlider.valueChanged.connect(
                    self.on_navigation_slider_changed
                )
                self.dockwidget.navhorizontalSlider.setVisible(True)
                self.dockwidget.navhorizontalSlider.setEnabled(False)
                
                # Prevent buttons from being triggered by Space when they have focus
                self.dockwidget.previousButton.setFocusPolicy(NO_FOCUS)
                self.dockwidget.nextButton.setFocusPolicy(NO_FOCUS)
                self.dockwidget.playButton.setFocusPolicy(NO_FOCUS)
                self.dockwidget.pauseButton.setFocusPolicy(NO_FOCUS)
                self.dockwidget.settingsButton.setFocusPolicy(NO_FOCUS)
                
                # Space bar shortcut for play/pause
                self.spacebar_shortcut = QShortcut(QKeySequence(KEY_SPACE), self.dockwidget)
                self.spacebar_shortcut.activated.connect(self.toggle_play_pause_from_spacebar)
                self.spacebar_shortcut.setEnabled(False)  # default until settings are loaded

                # Setup timer
                self.timer = QTimer(self.dockwidget)
                self.playback_interval_ms = QSettings().value("FeatureNavigator/playbackInterval", 1000, type=int)
                self.timer.setInterval(self.playback_interval_ms)
                self.timer.timeout.connect(self.advance_auto_play)

                # Setup default states
                self.dockwidget.previousButton.setEnabled(False)
                self.dockwidget.nextButton.setEnabled(False)
                self.dockwidget.playButton.setEnabled(False)
                self.dockwidget.pauseButton.setEnabled(False)
              
                self.dockwidget.closingPlugin.connect(self.onClosePlugin)

                # Prevent duplicate signal connections
                try:
                    QgsProject.instance().cleared.disconnect(self.clear_plugin_state)
                except TypeError:
                    pass

                try:
                    QgsProject.instance().layerWillBeRemoved.disconnect(
                        self.on_layer_will_be_removed
                    )
                except TypeError:
                    pass
                
                try:
                    QgsProject.instance().layersAdded.disconnect(
                        self.on_project_layers_added
                    )
                except TypeError:
                    pass

                # Clear plugin state safely when the active layer is removed
                QgsProject.instance().layerWillBeRemoved.connect(
                    self.on_layer_will_be_removed
                )
                
                # Keep the combo box empty when layers are added by loading/opening a project.
                QgsProject.instance().cleared.connect(self.clear_plugin_state)
                QgsProject.instance().layersAdded.connect(self.on_project_layers_added)
                                
            # Show the dockwidget
            self.iface.addDockWidget(LEFT_DOCK_WIDGET_AREA, self.dockwidget)
            self.dockwidget.errorLabel.setVisible(False)
            self.dockwidget.show()
            
            self.dockwidget.setFocusPolicy(STRONG_FOCUS)
            self.dockwidget.setFocus()
            
            # Apply saved space bar setting
            settings = QSettings()
            spacebar_enabled = settings.value("FeatureNavigator/enableSpacebarPlayPause", False, type=bool)
            if self.spacebar_shortcut is not None:
                self.spacebar_shortcut.setEnabled(spacebar_enabled)
            
            self.selected_features_only = settings.value(
                "FeatureNavigator/selectedFeaturesOnly",
                False,
                type=bool
            )
            
            self.loop_navigation_enabled = settings.value(
                "FeatureNavigator/loopNavigation",
                False,
                type=bool
            )
            
            self.nav_slider_enabled = settings.value(
                "FeatureNavigator/showNavigationSlider",
                True,
                type=bool
            )

            self.dockwidget.navhorizontalSlider.setVisible(self.nav_slider_enabled)

            self.clear_combo_layer_selection()
                
   
    def reset_feature_index(self, layer):
        """Reset the feature list and index when a new layer is selected."""

        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        self.dockwidget.selectedFeatureLabel.setVisible(False)
        self.dockwidget.selectedFeatureLabel.setText("")
        self.dockwidget.errorLabel.setVisible(False)
        self.dockwidget.pauseButton.setEnabled(False)
        self.dockwidget.mMapLayerComboBox.setEnabled(True)

        old_layer = self.safe_current_layer()
       
        if old_layer and old_layer != layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)

        if not layer:
            if old_layer:
                try:
                    old_layer.removeSelection()
                except RuntimeError:
                    pass

            self.current_layer = None
            self.feature_ids = []
            self.current_index = -1
            self.has_selected_feature = False

            self.dockwidget.errorLabel.setText("No layer selected")
            self.dockwidget.errorLabel.setVisible(True)
            self.disable_navigation()
            return

        if old_layer and old_layer != layer:
            try:
                old_layer.removeSelection()
            except RuntimeError:
                pass

        self.current_layer = layer
        self.reconnect_signal(
            layer.selectionChanged,
            self.on_layer_selection_changed
        )
        
        self.connect_layer_feature_signals(layer)

        if self.selected_features_only:
            self.selected_feature_ids_cache = list(self.current_layer.selectedFeatureIds())
        else:
            self.selected_feature_ids_cache = []

        self.has_selected_feature = False
        self.current_index = -1
        self.refresh_feature_list(preserve_position=False)
        return
    
    def on_project_layers_added(self, layers):
        """
        Keep the layer combo box empty when layers are added automatically.

        QgsMapLayerComboBox can auto-select the first available layer when the
        project/layer model changes. The plugin should only select a layer after
        the user explicitly chooses one from the combo box.
        """
        if self.user_has_selected_layer or self.current_layer is not None:
            return

        if not self.dockwidget:
            return

        QTimer.singleShot(0, self.clear_combo_layer_selection)
    
    def ensure_layer_visible(self, layer):
        """
        Ensure the selected layer and any parent groups are visible in the layer tree.

        Returns True if any visibility state was changed.
        """
        if not layer:
            return False

        try:
            layer_id = layer.id()
        except RuntimeError:
            return False

        root = QgsProject.instance().layerTreeRoot()
        layer_node = root.findLayer(layer_id)

        if layer_node is None:
            return False

        visibility_changed = False

        # Toggle the layer itself on if needed.
        if not layer_node.itemVisibilityChecked():
            layer_node.setItemVisibilityChecked(True)
            visibility_changed = True

        # Toggle parent groups on too. A checked layer inside an unchecked group
        # is still not visible on the map canvas.
        parent = layer_node.parent()

        while parent and parent.nodeType() == QgsLayerTreeNode.NodeGroup:
            if not parent.itemVisibilityChecked():
                parent.setItemVisibilityChecked(True)
                visibility_changed = True

            parent = parent.parent()

        return visibility_changed
    
    def reconnect_signal(self, signal, slot):
        """Safely reconnect a Qt signal."""
        try:
            signal.disconnect(slot)
        except TypeError:
            pass

        signal.connect(slot)

    def connect_layer_selection_signal(self, layer):
        """Connect to the selected layer's selectionChanged signal."""
        if not layer:
            return

        try:
            layer.selectionChanged.connect(self.on_layer_selection_changed)
        except TypeError:
            # Already connected
            pass

    def disconnect_layer_selection_signal(self, layer):
        """Disconnect from the previous layer's selectionChanged signal."""
        if not layer:
            return

        try:
            layer.selectionChanged.disconnect(self.on_layer_selection_changed)
        except TypeError:
            # Was not connected
            pass
            
    def next_feature(self):
        """Move forward in the feature list."""
        if not self.feature_ids:
            return

        if not self.has_selected_feature:
            # First click/play should go to feature 1.
            self.current_index = 0
            self.has_selected_feature = True
        elif self.current_index >= len(self.feature_ids) - 1:
            if not self.loop_navigation_enabled:
                self.stop_auto_play()
                self.iface.messageBar().pushInfo(
                    "Feature Navigator",
                    "The final feature of this layer has been reached."
                )
                return

            self.current_index = 0
        else:
            self.current_index += 1

        self.dockwidget.selectedFeatureLabel.setVisible(True)
        self.select_feature()
    
    def on_layer_selection_changed(self, selected, deselected, clearAndSelect):
        """Jump navigator index to a user-selected feature in the current layer."""
        if self.ignore_selection_change:
            return

        layer = self.safe_current_layer()
        if layer is None:
            self.clear_plugin_state()
            return

        if self.selected_features_only:
            self.selected_feature_ids_cache = list(layer.selectedFeatureIds())
            self.refresh_feature_list(preserve_position=False)
            return

        if not self.feature_ids:
            return

        if not selected:
            return

        selected_ids = layer.selectedFeatureIds()
        if not selected_ids:
            return

        selected_fid = next(iter(selected_ids), None)
        if selected_fid not in self.feature_id_to_index:
            return

        self.current_index = self.feature_id_to_index[selected_fid]
        self.has_selected_feature = True
        self.dockwidget.selectedFeatureLabel.setVisible(True)
        self.update_selected_feature_label()
        self.update_navigation_slider()
    
    def previous_feature(self):
        """Move backward in the feature list."""
        if not self.feature_ids:
            return

        if not self.has_selected_feature:
            # First previous click should go to the last feature.
            self.current_index = len(self.feature_ids) - 1
            self.has_selected_feature = True
        elif self.current_index <= 0:
            if not self.loop_navigation_enabled:
                self.stop_auto_play()
                self.iface.messageBar().pushInfo(
                    "Feature Navigator",
                    "The first feature of this layer has been reached."
                )
                return

            self.current_index = len(self.feature_ids) - 1
        else:
            self.current_index -= 1

        self.dockwidget.selectedFeatureLabel.setVisible(True)
        self.select_feature()
        
    def update_navigation_slider(self):
        """Synchronise the navigation slider with the current feature position."""
        if not self.dockwidget:
            return

        slider = self.dockwidget.navhorizontalSlider

        self.ignore_slider_change = True
        try:
            if not self.feature_ids:
                slider.setMinimum(0)
                slider.setMaximum(0)
                slider.setValue(0)
                slider.setEnabled(False)
                return

            slider.setMinimum(0)
            slider.setMaximum(len(self.feature_ids) - 1)
            slider.setEnabled(self.nav_slider_enabled and len(self.feature_ids) > 1)

            if self.current_index >= 0:
                safe_index = max(0, min(self.current_index, len(self.feature_ids) - 1))
                slider.setValue(safe_index)
            else:
                slider.setValue(0)
        finally:
            self.ignore_slider_change = False
    
    def on_navigation_slider_changed(self, value):
        """Navigate to the feature represented by the slider position."""
        if self.ignore_slider_change:
            return

        if not self.feature_ids:
            return

        if value < 0 or value >= len(self.feature_ids):
            return

        if self.timer is not None and self.timer.isActive():
            self.stop_auto_play()

        self.ensure_current_layer_visible_with_notification()

        self.current_index = value
        self.has_selected_feature = True
        self.dockwidget.selectedFeatureLabel.setVisible(True)
        self.select_feature()
     
    def select_feature(self):
        """Select and zoom to the current feature."""
        layer = self.safe_current_layer()
        if layer is None or not self.feature_ids:
            self.feature_ids = []
            self.current_index = -1
            self.has_selected_feature = False
            self.disable_navigation()
            return

        if self.current_index < 0 or self.current_index >= len(self.feature_ids):
            self.current_index = -1
            self.has_selected_feature = False
            self.disable_navigation()
            return

        fid = self.feature_ids[self.current_index]

        self.iface.setActiveLayer(layer)

        self.ensure_current_layer_visible_with_notification()

        self.ignore_selection_change = True
        try:
            layer.selectByIds([fid])
        except RuntimeError:
            self.clear_plugin_state()
            return
        finally:
            self.ignore_selection_change = False

        feature = layer.getFeature(fid)

        if not feature or not feature.isValid():
            self.update_selected_feature_label()
            self.update_navigation_slider()
            return

        geom = feature.geometry()

        if geom and not geom.isNull() and not geom.isEmpty():
            buffer_size = QSettings().value(
                "FeatureNavigator/zoomBuffer",
                1.0,
                type=float
            )
            self.iface.mapCanvas().setExtent(
                geom.boundingBox().buffered(buffer_size)
            )

        self.update_selected_feature_label()
        self.update_navigation_slider()
    
    def update_selected_feature_label(self):
        """Update the 'Feature X of Y' label."""
        if self.current_index >= 0 and self.feature_ids:
            current = self.current_index + 1
            total = len(self.feature_ids)
            self.dockwidget.selectedFeatureLabel.setText(f"Feature {current} of {total}")
    
    def toggle_play_pause_from_spacebar(self):
        """Toggle play/pause using the space bar shortcut."""
        if not self.dockwidget:
            return

        settings = QSettings()
        enabled = settings.value("FeatureNavigator/enableSpacebarPlayPause", False, type=bool)
        if not enabled:
            return

        if not self.feature_ids or len(self.feature_ids) <= 1:
            return

        if self.timer is not None and self.timer.isActive():
            self.stop_auto_play()
        else:
            self.start_auto_play()
        
    def start_auto_play(self):
        """Start or resume automated navigation."""
        if not self.feature_ids:
            return

        if not self.has_selected_feature:
            self.next_feature()
            self.remaining_interval_ms = self.playback_interval_ms

        interval_to_start = (
            self.remaining_interval_ms
            if self.remaining_interval_ms is not None
            else self.playback_interval_ms
        )

        if self.timer is not None:
            self.timer.start(interval_to_start)
            self.playback_elapsed_timer.restart()

        self.dockwidget.playButton.setEnabled(False)
        self.dockwidget.pauseButton.setEnabled(True)
        self.dockwidget.nextButton.setEnabled(False)
        self.dockwidget.previousButton.setEnabled(False)
        self.dockwidget.mMapLayerComboBox.setEnabled(False)


    def stop_auto_play(self):
        """Pause automated navigation and preserve the remaining countdown."""
        if self.timer is not None and self.timer.isActive():
            elapsed_ms = self.playback_elapsed_timer.elapsed()
            current_interval = self.timer.interval()

            self.remaining_interval_ms = max(1, current_interval - elapsed_ms)
            self.timer.stop()

        self.dockwidget.playButton.setEnabled(True)
        self.dockwidget.pauseButton.setEnabled(False)
        self.dockwidget.mMapLayerComboBox.setEnabled(True)

        if len(self.feature_ids) > 1:
            self.dockwidget.nextButton.setEnabled(True)
            self.dockwidget.previousButton.setEnabled(True)
    
    def advance_auto_play(self):
        """Move to the next feature during autoplay and reset the countdown."""
        self.remaining_interval_ms = self.playback_interval_ms
        self.next_feature()

        if self.timer is not None and self.timer.isActive():
            self.timer.start(self.playback_interval_ms)
            self.playback_elapsed_timer.restart()
                
    def disable_navigation(self):
        """Disable all navigation-related controls."""
        if not self.dockwidget:
            return

        self.dockwidget.previousButton.setEnabled(False)
        self.dockwidget.nextButton.setEnabled(False)
        self.dockwidget.playButton.setEnabled(False)
        self.dockwidget.pauseButton.setEnabled(False)


    def show_settings_dialog(self):
        """Open settings dialog and apply only if OK was clicked."""
        dialog = FeatureNavigatorSettingsDialog()

        settings = QSettings()
        current_interval_ms = settings.value("FeatureNavigator/playbackInterval", 1000, type=int)
        current_zoom_buffer = settings.value("FeatureNavigator/zoomBuffer",1.0,type=float)
        current_spacebar_enabled = settings.value("FeatureNavigator/enableSpacebarPlayPause", False, type=bool)
        current_selected_only = settings.value("FeatureNavigator/selectedFeaturesOnly", False, type=bool)
        current_loop_enabled = settings.value("FeatureNavigator/loopNavigation",False,type=bool)
        current_nav_slider_enabled = settings.value("FeatureNavigator/showNavigationSlider",True,type=bool)
        
        dialog.speedSpinBox.setValue(current_interval_ms // 1000)
        dialog.bufferSpinBox.setValue(int(round(current_zoom_buffer)))
        dialog.spacebarcheckBox.setChecked(current_spacebar_enabled)
        dialog.selectedfeaturescheckBox.setChecked(current_selected_only)
        dialog.loopcheckBox.setChecked(current_loop_enabled)
        dialog.navcheckBox.setChecked(current_nav_slider_enabled)

        if dialog.exec() == DIALOG_ACCEPTED:
            new_interval_ms = dialog.speedSpinBox.value() * 1000
            new_buffer_m = dialog.bufferSpinBox.value()
            new_spacebar_enabled = dialog.spacebarcheckBox.isChecked()
            new_selected_only = dialog.selectedfeaturescheckBox.isChecked()
            new_loop_enabled = dialog.loopcheckBox.isChecked()
            new_nav_slider_enabled = dialog.navcheckBox.isChecked()

            settings.setValue("FeatureNavigator/playbackInterval", new_interval_ms)
            settings.setValue("FeatureNavigator/zoomBuffer", new_buffer_m)
            settings.setValue("FeatureNavigator/enableSpacebarPlayPause", new_spacebar_enabled)
            settings.setValue("FeatureNavigator/selectedFeaturesOnly", new_selected_only)
            settings.setValue("FeatureNavigator/loopNavigation", new_loop_enabled)
            settings.setValue("FeatureNavigator/showNavigationSlider", new_nav_slider_enabled)
            

            old_selected_only = self.selected_features_only
            was_playing = self.timer is not None and self.timer.isActive()

            self.playback_interval_ms = new_interval_ms
            self.remaining_interval_ms = new_interval_ms

            if self.timer is not None:
                self.timer.setInterval(new_interval_ms)

            if self.spacebar_shortcut is not None:
                self.spacebar_shortcut.setEnabled(new_spacebar_enabled)

            self.selected_features_only = new_selected_only
            self.loop_navigation_enabled = new_loop_enabled
            
            self.nav_slider_enabled = new_nav_slider_enabled

            if self.dockwidget is not None:
                self.dockwidget.navhorizontalSlider.setVisible(
                    self.nav_slider_enabled
                )
                self.update_navigation_slider()

            if self.selected_features_only and self.current_layer:
                self.selected_feature_ids_cache = list(self.current_layer.selectedFeatureIds())
            else:
                self.selected_feature_ids_cache = []

            # Preserve the current navigation position when changing simple settings
            # such as zoom buffer, playback speed, or spacebar behaviour.
            # If selected-features-only mode changed, rebuild from the new feature set.
            selection_mode_changed = old_selected_only != new_selected_only

            self.refresh_feature_list(
                preserve_position=not selection_mode_changed
            )

            if was_playing and self.feature_ids:
                self.timer.start()
    
    def clear_combo_layer_selection(self):
        """Keep the layer combo box empty until the user explicitly selects a layer."""
        if not self.dockwidget:
            return

        self.suppress_layer_change = True
        try:
            self.dockwidget.mMapLayerComboBox.setLayer(None)
        finally:
            self.suppress_layer_change = False

        self.user_has_selected_layer = False
        self.reset_feature_index(None)


    def on_combo_layer_changed(self, layer):
        """Handle only user-driven layer selections from the combo box."""
        if self.suppress_layer_change:
            return

        self.user_has_selected_layer = layer is not None
        self.reset_feature_index(layer)


    def connect_layer_feature_signals(self, layer):
        """Connect to layer signals that affect the feature list."""
        if not layer:
            return

        self.reconnect_signal(
            layer.featureAdded,
            self.on_layer_feature_added
        )

        try:
            layer.featureDeleted.connect(self.on_layer_feature_deleted)
        except TypeError:
            pass
            
    def disconnect_layer_feature_signals(self, layer):
        """Disconnect from layer signals that affect the feature list."""
        if not layer:
            return

        try:
            layer.featureAdded.disconnect(self.on_layer_feature_added)
        except TypeError:
            pass

        try:
            layer.featureDeleted.disconnect(self.on_layer_feature_deleted)
        except TypeError:
            pass


    def refresh_feature_list(self, preserve_position=True, deleted_fid=None):
        """Rebuild feature id list while preserving current navigation position."""
        layer = self.safe_current_layer()
        if not layer:
            self.current_layer = None
            self.feature_ids = []
            self.feature_id_to_index = {}
            self.current_index = -1
            self.has_selected_feature = False
            self.disable_navigation()
            self.update_navigation_slider()
            return

        old_feature_ids = list(self.feature_ids)
        old_index = self.current_index

        current_fid = None
        if (
            preserve_position
            and self.has_selected_feature
            and 0 <= self.current_index < len(self.feature_ids)
        ):
            current_fid = self.feature_ids[self.current_index]

        if self.selected_features_only:
            self.feature_ids = list(self.selected_feature_ids_cache)
        else:
            request = (
                QgsFeatureRequest()
                .setFlags(QgsFeatureRequest.NoGeometry)
                .setNoAttributes()
            )
            self.feature_ids = [feature.id() for feature in layer.getFeatures(request)]
            
        # Feature IDs are used only as a stable in-session navigation order.
        # Provider FIDs are not guaranteed to be sequential or persistent.
        self.feature_ids.sort()
        self.feature_id_to_index = {
            fid: idx for idx, fid in enumerate(self.feature_ids)
        }
        num_features = len(self.feature_ids)

        if num_features == 0:
            self.feature_id_to_index = {}
            self.current_index = -1
            self.has_selected_feature = False
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
            if self.selected_features_only:
                self.dockwidget.errorLabel.setText("No selected features in currently selected layer")
            else:
                self.dockwidget.errorLabel.setText("No features in currently selected layer")
            self.dockwidget.errorLabel.setVisible(True)

            if self.timer is not None and self.timer.isActive():
                self.timer.stop()

            self.disable_navigation()
            self.dockwidget.mMapLayerComboBox.setEnabled(True)
            self.update_navigation_slider()
            return

        elif preserve_position and current_fid in self.feature_id_to_index:
            self.current_index = self.feature_id_to_index[current_fid]
            self.has_selected_feature = True

        elif deleted_fid is not None and old_feature_ids:
            deleted_index = old_feature_ids.index(deleted_fid) if deleted_fid in old_feature_ids else old_index

            if deleted_index >= len(self.feature_ids):
                self.current_index = len(self.feature_ids) - 1
            else:
                self.current_index = deleted_index

            self.has_selected_feature = True
        else:
            if not preserve_position:
                self.current_index = -1
                self.has_selected_feature = False
            elif old_index < 0:
                self.current_index = -1
                self.has_selected_feature = False
            elif old_index >= len(self.feature_ids):
                self.current_index = len(self.feature_ids) - 1
            else:
                self.current_index = old_index

        if num_features == 1:
            self.dockwidget.errorLabel.setText("Only single feature in selected layer")
            self.dockwidget.errorLabel.setVisible(True)
        else:
            self.dockwidget.errorLabel.setVisible(False)

        is_playing = self.timer is not None and self.timer.isActive()

        self.dockwidget.playButton.setEnabled(num_features > 1 and not is_playing)
        self.dockwidget.pauseButton.setEnabled(num_features > 1 and is_playing)
        self.dockwidget.previousButton.setEnabled(num_features > 1 and not is_playing)
        self.dockwidget.nextButton.setEnabled(num_features > 1 and not is_playing)

        if self.current_index >= 0 and self.has_selected_feature:
            self.dockwidget.selectedFeatureLabel.setVisible(True)
            self.update_selected_feature_label()
        else:
            self.current_index = -1
            self.has_selected_feature = False
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
        
        self.update_navigation_slider()


    def on_layer_feature_added(self, fid):
        """Triggered when a feature is added."""
        if self.ignore_selection_change:
            return

        self.refresh_feature_list(preserve_position=True)


    def on_layer_feature_deleted(self, fid):
        """Triggered when a feature is deleted."""
        if self.ignore_selection_change:
            return

        # Keep selected-feature-only mode clean if the deleted feature was selected.
        if fid in self.selected_feature_ids_cache:
            self.selected_feature_ids_cache.remove(fid)

        self.refresh_feature_list(preserve_position=True, deleted_fid=fid)

        # Do not auto-select or auto-zoom after deletion.
        # Keep the current index so the next/previous click continues from the
        # deleted feature's former position instead of restarting navigation.
        if self.current_index >= 0 and self.feature_ids:
            self.has_selected_feature = True
            self.dockwidget.selectedFeatureLabel.setVisible(True)
            self.update_selected_feature_label()
        else:
            self.has_selected_feature = False
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
    
    def set_navigation_enabled(self, enabled):
        """Enable or disable manual navigation controls."""
        self.dockwidget.previousButton.setEnabled(enabled)
        self.dockwidget.nextButton.setEnabled(enabled)
        self.dockwidget.playButton.setEnabled(enabled)
        self.dockwidget.pauseButton.setEnabled(False)
        
    def safe_current_layer(self):
        """Return current layer if still valid, otherwise None."""
        layer = getattr(self, "current_layer", None)

        if layer is None:
            self.current_layer = None
            return None

        try:
            _ = layer.id()
            return layer
        except RuntimeError:
            self.current_layer = None
            return None
    
    def on_layer_will_be_removed(self, layer_id):
        """Clear navigator state before the active layer is removed."""
        layer = self.safe_current_layer()

        if layer is None:
            self.clear_plugin_state()
            return

        try:
            if layer.id() == layer_id:
                self.clear_plugin_state()
        except RuntimeError:
            self.clear_plugin_state()
    
    def ensure_current_layer_visible_with_notification(self):
        """Ensure the current layer is visible and notify the user if visibility changed."""
        layer = self.safe_current_layer()
        if layer is None:
            return False

        visibility_changed = self.ensure_layer_visible(layer)

        if visibility_changed:
            self.iface.messageBar().pushInfo(
                "Feature Navigator",
                f"{layer.name()} layer visibility has been toggled on"
            )

        return visibility_changed

    def clear_plugin_state(self):
        """Clear plugin state safely when project/layers are removed."""
        if self.timer is not None and self.timer.isActive():
            self.timer.stop()

        old_layer = self.safe_current_layer()
        if old_layer:
            self.disconnect_layer_selection_signal(old_layer)
            self.disconnect_layer_feature_signals(old_layer)
            try:
                old_layer.removeSelection()
            except RuntimeError:
                pass

        self.current_layer = None
        self.feature_ids = []
        self.current_index = -1
        self.has_selected_feature = False

        if self.dockwidget:
            self.dockwidget.selectedFeatureLabel.setVisible(False)
            self.dockwidget.selectedFeatureLabel.setText("")
            self.dockwidget.errorLabel.setVisible(False)

            self.suppress_layer_change = True
            try:
                self.dockwidget.mMapLayerComboBox.setLayer(None)
            finally:
                self.suppress_layer_change = False

            self.user_has_selected_layer = False
            self.dockwidget.mMapLayerComboBox.setEnabled(True)
            self.disable_navigation()
            self.update_navigation_slider()
                


