# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureNavigationDock
                                 A QGIS plugin
 This plugin allows the user to navigate through features within a selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Isaac Thompson
        email                : iswaldeen@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtGui import QDesktopServices

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'feature_navigation_dock_dialog_base.ui'))


class FeatureNavigationDockSettingsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(FeatureNavigationDockSettingsDialog, self).__init__(parent)

        self.setupUi(self)
        # Ensure the settings dialog opens at its intended size
        self.resize(560, 620)

        self._configure_help_button()
        self._configure_dialog_widgets()

        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.helpButton.clicked.connect(self.open_help)
    
    def _configure_help_button(self):
        """Apply a theme-aware icon and circular styling to the help button."""
        if not hasattr(self, "helpButton") or self.helpButton is None:
            return

        is_dark = self._is_dark_ui()

        icon_name = "question_mark_darkmode.png" if is_dark else "question_mark.png"
        icon_path = os.path.join(os.path.dirname(__file__), "icons", icon_name)

        if os.path.exists(icon_path):
            self.helpButton.setIcon(QtGui.QIcon(icon_path))

        self.helpButton.setFixedSize(34, 34)
        self.helpButton.setIconSize(self.helpButton.size() * 0.58)
        self.helpButton.setToolTip("Help")

        self.helpButton.setStyleSheet(
            self._round_icon_button_stylesheet("helpButton", is_dark)
        )


    def _configure_dialog_widgets(self):
        """Apply runtime-only widget settings that should not live in the .ui file."""
        widget_tooltips = {
            "selectedfeaturescheckBox": "Navigate only through currently selected features in the active layer.",
            "spacebarcheckBox": "Allow the space bar to pause and resume autoplay.",
            "loopcheckBox": "Restart playback automatically after the final feature.",
            "navcheckBox": "Show or hide the navigation slider in the main plugin dialog.",
            "speedSpinBox": "Number of seconds between features during autoplay.",
            "bufferSpinBox": "Additional map extent, in metres, around the feature when zooming.",
        }

        for object_name, tooltip in widget_tooltips.items():
            widget = self.findChild(QtWidgets.QWidget, object_name)
            if widget is None:
                continue

            widget.setToolTip(tooltip)
            widget.setAccessibleName(tooltip)
                
    @staticmethod
    def _is_dark_ui():
        """
        Return True when the active QGIS/Qt palette appears dark.

        This is more reliable than checking only the QGIS theme name because
        QGIS 4 / Qt6 may use the OS colour scheme while the theme remains 'default'.
        """
        app = QtWidgets.QApplication.instance()
        if app is None:
            return False

        if hasattr(QtGui.QPalette, "ColorRole"):
            window_role = QtGui.QPalette.ColorRole.Window
        else:
            window_role = QtGui.QPalette.Window

        return app.palette().color(window_role).lightness() < 128
     
    @staticmethod
    def _round_icon_button_stylesheet(button_object_name, is_dark):
        """Return circular button styling for light and dark QGIS themes."""
        if is_dark:
            background = "#5a5a5a"
            hover = "#686868"
            pressed = "#4d4d4d"
            border = "#3a3a3a"
        else:
            # Soft green theme to match the plugin styling
            background = "#f7fbf7"
            hover = "#e5f3e5"
            pressed = "#cfe7cf"
            border = "#b8d8bd"

        return f"""
            QPushButton#{button_object_name} {{
                border-radius: 17px;
                border: 1px solid {border};
                background-color: {background};
                background-image: none;
                padding: 4px;
            }}

            QPushButton#{button_object_name}:hover {{
                background-color: {hover};
            }}

            QPushButton#{button_object_name}:pressed {{
                background-color: {pressed};
            }}
        """
        
    def open_help(self):
        """Open the Feature Navigation Dock help file in the user's default browser."""

        help_path = os.path.join(
            os.path.dirname(__file__),
            "help",
            "help.html"
        )

        if not os.path.exists(help_path):
            QtWidgets.QMessageBox.warning(
                self,
                "Feature Navigation Dock",
                "The help document could not be found."
            )
            return

        QDesktopServices.openUrl(QUrl.fromLocalFile(os.path.realpath(help_path)))